# Generated by Django 4.1.3 on 2022-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='abs_days',
            field=models.TextField(null=True),
        ),
    ]
