# Generated by Django 4.1.3 on 2022-12-22 18:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_day_day_day_abs_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='abs_days',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1), max_length=30, null=True, size=11),
        ),
    ]
