# Generated by Django 4.1.3 on 2022-12-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_day_abs_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='abs_days',
            field=models.TextField(null=True),
        ),
    ]
