# Generated by Django 4.1.3 on 2022-12-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_day_abs_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
